channels:
  - pytorch
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.11.7
  - aiosignal=1.3.1
  - anyio=4.6.2.post1
  - appdirs=1.4.4
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.3
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.1
  - aws-c-io=0.15.2
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.1
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.5
  - aws-sdk-cpp=1.11.449
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cpython=3.12.7
  - cycler=0.12.1
  - datasets=2.14.4
  - debugpy=1.8.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.16.1
  - fonttools=4.54.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.10.0
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - huggingface_hub=0.26.2
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.29.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=19.1.2
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libparquet=18.0.0
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libutf8proc=2.8.0
  - libuv=1.49.2
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxgboost=2.1.2
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - propcache=0.2.0
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.2
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pycparser=2.22
  - pygments=2.18.0
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.35.1
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - safetensors=0.4.5
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setproctitle=1.3.4
  - setuptools=75.1.0
  - six=1.16.0
  - sleef=3.7
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - sympy=1.13.3
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.20.3
  - tomli=2.0.2
  - torchvision=0.20.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - transformers=4.46.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wandb=0.18.7
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xgboost=2.1.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.20.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - distro==1.9.0
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.68.0
      - h5py==3.12.1
      - html-sanitizer==2.4.4
      - jiter==0.7.0
      - kagglehub==0.3.3
      - keras==3.6.0
      - libclang==18.1.1
      - lxml==5.3.0
      - lxml-html-clean==0.3.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - openai==1.53.0
      - opt-einsum==3.4.0
      - optree==0.13.1
      - protobuf==4.25.5
      - psycopg2-binary==2.9.10
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - python-dotenv==1.0.1
      - python-slugify==8.0.4
      - rich==13.9.4
      - sentry-sdk==2.18.0
      - smmap==5.0.1
      - sqlalchemy==2.0.36
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - text-unidecode==1.3
      - tqdm==4.66.5
      - ucimlrepo==0.0.7
      - werkzeug==3.1.3
      - wrapt==1.17.0
