CREATE TABLE source (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE url (
	id SERIAL PRIMARY KEY,
    source_id INTEGER REFERENCES source(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    features JSONB,
    is_phishing BOOLEAN NOT NULL,
    is_online BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
